name: Generate Pages
on:
  workflow_dispatch: # เพื่อให้เรากดปุ่มรันเองได้
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run Generator Script
        run: python generate.py
      - name: Commit and Push Pages
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Generate Batch 1 Pages" || exit 0
          git push
